WITH BIKE AS(
  SELECT
RIDE_ID
,REPLACE(STARTED_AT, '"', '') AS STARTED_AT
,REPLACE(ENDED_AT, '"', '') AS ENDED_AT
,START_STATION_NAME
,START_STATION_ID
,END_STATION_NAME
,END_STATION_ID
,START_LAT
,START_LON
,END_LAT
,END_LON
,MEMBER_CSUAL
from {{ source('demo', 'bike') }}
where RIDE_ID != '"bikeid"' and RIDE_ID != 'bikeid'-- and STARTED_AT != 'starttime' and STARTED_AT != '"starttime"'
)
SELECT * FROM BIKE
