WITH TRIPS AS (
  SELECT 
    RIDE_ID
--    ,RIDEABLE_TYPE
    ,DATE(TO_TIMESTAMP(STARTED_AT)) AS TRIP_DATE
    ,START_STATION_ID
    ,END_STATION_ID
    ,MEMBER_CSUAL AS MEMBER_CASUAL
    ,TIMESTAMPDIFF(second, TO_TIMESTAMP(STARTED_AT), TO_TIMESTAMP(ENDED_AT)) AS TRIP_DURATION
  FROM {{ ref('stg_bike') }}
  where RIDE_ID != '"bikeid"' and RIDE_ID != 'bikeid'
)
SELECT *
FROM TRIPS